server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/produtos_yzbv
    password: QAPJcNUONrgVZupk3ujcWl1nNAG1cVY3
    username: admin
    driverClassName: org.postgresql.Driver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: silvas.pr@gmail.com
    password: "bbul jtmq otqv evgd"
    port: '587'
